npcid = npcs.link
max_texts = 6
text[0] = "@VA_LINK1"
text[1] = "Hey there buddy! I am link! From the hit game Legend of Zelda!"
text[2] = "@VA_LINK2"
text[3] = "Most people don't know this, but I sound just like Gilbert 'Ruben' Ruiz! My secret is safe with you though!"
text[4] = "@VA_LINK3"
text[5] = "Anyway, i gotta skedaddle, I got.... ghouls... and evil mages.... to.... \"fight\"... Toodaloo!"
text[6] = "@LINK_STOP_VA"